diagrams: clean rate-limiter post-delay interval-backoff

rate-limiter:
	swirly --scale=200 rate-limiter.txt rate-limiter.png
	swirly --scale=200 rate-limit-five-tick.txt rate-limit-five-tick.png

post-delay:
	swirly --scale=200 post-delay.txt post-delay.png

interval-backoff:
	swirly --scale=200 interval-backoff.txt interval-backoff.png

clean:
	rm -f *.png