diagrams: clean
	swirly --scale=200 rate-limiter.txt rate-limiter.png
	swirly --scale=200 rate-limit-five-tick.txt rate-limit-five-tick.png
	swirly --scale=200 post-delay.txt post-delay.png

clean:
	rm -f *.png